# ============================================================
# SECTION 9 // REMOTE LAPTOP
# ============================================================

# ThinkPad X240 internal display
monitor = eDP-1,1366x768@60,0x0,1

# Laptop input
input {
    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

# Laptop lid behavior
bindl = , switch:on:Lid Switch, exec, systemctl suspend
