[General]

passwordCharacter=•
passwordMask=true
passwordInputWidth=0.31
passwordInputBackground=#030e15
passwordInputRadius=2
passwordInputCursorVisible=true
passwordInputBorderWidth=2
passwordInputBorderColor=#5bdaeb
passwordFontSize=18
passwordCursorColor=#5bdaeb
passwordTextColor=#daeef2
passwordAllowEmpty=false

cursorBlinkAnimation=true

showSessionsByDefault=false
sessionsFontSize=13

showUsersByDefault=true
usersFontSize=15
showUserRealNameByDefault=false

background=
backgroundFill=#02080e
backgroundFillMode=aspect

basicTextColor=#5bdaeb

wrongPasswordBorderColor=#ff5b69
wrongPasswordBorderRadius=0

blurRadius=0
hideCursor=true

font=monospace
