[General]
passwordCharacter=*
passwordMask=true
passwordInputWidth=0.5
passwordInputBackground=
passwordInputRadius=
passwordInputCursorVisible=true
passwordFontSize=69
passwordCursorColor=random
passwordTextColor=
passwordAllowEmpty=false

cursorBlinkAnimation=true

showSessionsByDefault=true
sessionsFontSize=14

showUsersByDefault=true
usersFontSize=14
showUserRealNameByDefault=true

background=
backgroundFill=#000000
backgroundFillMode=aspect

basicTextColor=#808080

blurRadius=0

hideCursor=false
